#include "crumbs_crc.h"

/* Use the C99 implementation generated by pycrc. */
#include "crc8_nibble.h"

crumbs_crc8_t crumbs_crc8(const uint8_t *data, size_t len)
{
    if (data == NULL || len == 0)
    {
        return 0u;
    }

    /* Delegate to the generated implementation. */
    return (crumbs_crc8_t)crc8_nibble_calculate(data, len);
}
