name=CRUMBS
version=0.12.0
author=Cameron
maintainer=Cameron <cambrooks3393@gmail.com>
sentence=CRUMBS: A communication library for managing data exchange between peripheral devices and a controller using serialization over I2C.
paragraph=The CRUMBS library is designed to handle the communication for small modular embedded systems. It uses a universal data structure and serialization for efficient and scalable I2C communication between multiple peripheral devices and the controller.
category=Communication
url=https://github.com/feastorg/CRUMBS
architectures=*
frameworks=arduino
license=AGPL-3.0-or-later
