[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags = 
	-DCRUMBS_MAX_HANDLERS=8
	-I ..
lib_deps = 
	cameronbrooks11/CRUMBS@^0.12.2

[env:nanoatmega328old]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 57600
monitor_speed = 115200
build_flags =
    -DCRUMBS_MAX_HANDLERS=8
    -I ..
lib_deps =
    cameronbrooks11/CRUMBS@^0.12.2

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
	-DCRUMBS_MAX_HANDLERS=8
	-I ..
lib_deps =
	cameronbrooks11/CRUMBS@^0.12.2

[platformio]
default_envs = nanoatmega328new
