#ifndef CRUMBS_VERSION_H
#define CRUMBS_VERSION_H

#define CRUMBS_VERSION_MAJOR 0
#define CRUMBS_VERSION_MINOR 12
#define CRUMBS_VERSION_PATCH 2
#define CRUMBS_VERSION_STRING "0.12.2"
#define CRUMBS_VERSION 1202 // major*10000 + minor*100 + patch

#endif // CRUMBS_VERSION_H
