#ifndef CRUMBS_CRC_H
#define CRUMBS_CRC_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint8_t crumbs_crc8_t;

/**
 * @brief Compute CRC-8 over a contiguous buffer.
 *
 * The polynomial/parameters are defined by the underlying crc8_nibble*
 * implementation generated by pycrc
 *
 * @param data Pointer to input buffer.
 * @param len  Number of bytes.
 * @return CRC-8 of the buffer.
 */
crumbs_crc8_t crumbs_crc8(const uint8_t *data, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* CRUMBS_CRC_H */
