#ifndef CRUMBS_VERSION_H
#define CRUMBS_VERSION_H

#define CRUMBS_VERSION_MAJOR 0
#define CRUMBS_VERSION_MINOR 12
#define CRUMBS_VERSION_PATCH 1
#define CRUMBS_VERSION_STRING "0.12.1"
#define CRUMBS_VERSION 1201 // major*10000 + minor*100 + patch

#endif // CRUMBS_VERSION_H
